name: evera
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_auth: ^5.3.1
  image_picker: ^1.1.2
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  carousel_slider: ^5.0.0
  location: ^7.0.1
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  supabase_flutter: ^2.8.1
  shared_preferences: ^2.3.3
  cryptography: ^2.7.0
  table_calendar: ^3.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
